user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 1024; # Aumentado para suportar mais conexões
}

http {
    access_log /var/log/nginx/access.log; # Adicionado log de acesso
    error_log /var/log/nginx/error.log;   # Adicionado log de erro

    server {
        listen 8080;
        client_max_body_size 20M; # Aumentado para suportar múltiplos arquivos
        client_body_timeout 300s; # Aumentado para conexões lentas
        fastcgi_read_timeout 300s; # Aumentado para processamento PHP
        root /var/www/public;
        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass php-fpm:9000; # Alterado para nome do serviço Docker
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        location ~* \.(env|log|conf|bak|sql)$ {
            deny all;
            return 403;
        }
    }
}
