[supervisord]
nodaemon=true
loglevel=info

[program:php-fpm]
command=php-fpm -F
stdout_logfile=/var/www/storage/logs/php-fpm.log
stderr_logfile=/var/www/storage/logs/php-fpm.log
autorestart=true

[program:nginx]
command=nginx -g "daemon off;"
stdout_logfile=/var/www/storage/logs/nginx.log
stderr_logfile=/var/www/storage/logs/nginx.log
autorestart=true

; --- NOVO PROGRAMA PARA LOGS DO LARAVEL ---
[program:laravel-logs]
command=tail -f /var/www/storage/logs/laravel.log
stdout_logfile=/var/www/storage/logs/laravel-supervisor.log
stderr_logfile=/var/www/storage/logs/laravel-supervisor-error.log
autorestart=true
