name: Processar Fila Laravel

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch: 

jobs:
  ping_queue:
    runs-on: ubuntu-latest
    steps:
      - name: Executar e Ver Logs da Fila
        run: |
          # Realiza a chamada e imprime diretamente no console do GitHub
          echo "Iniciando processamento às $(date)"
          
          # -i faz o curl mostrar os headers (ajuda a ver o status HTTP)
          # A resposta do seu Controller aparecerá logo abaixo
          curl -L "https://api.diariodoestilo.site/api/processar-fila?token=f47ac10b-58cc-4372-a567-0e02b2c3d479"
