name: Processar Fila Laravel

on:
  schedule:
    # Executa a cada 10 minutos
    - cron: '*/10 * * * *'
  workflow_dispatch: # Permite rodar manualmente para teste

jobs:
  ping_queue:
    runs-on: ubuntu-latest
    steps:
      - name: Hit Queue Script
        run: |
          curl -s -L "https://apii.diariodoestilo.site/queue_worker.php"
